version: 2
updates:
  - package-ecosystem: docker
    directory: "/windows/nanoserver-1809"
    schedule:
      interval: daily
    reviewers:
      - "coreyjonoliver"
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: "/windows/nanoserver-ltsc2022"
    schedule:
      interval: daily
    reviewers:
      - "coreyjonoliver"
    labels:
      - dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - "coreyjonoliver"
    labels:
      - dependencies
